### PR TITLE
Scala 2.13.8 draft release notes

### PR DESCRIPTION
**Pull request by SethTisue**
feedback on contents and wordings in notes are welcome — comment here

discussion on contents and timing of the release itself is on https://contributors.scala-lang.org/t/scala-2-13-8-release-planning/5487

### CODE REVIEW

**Comment by som-snytt** [comment]
Regressions я us!

**Comment by SethTisue** [comment]
Well, we did merge 113 PRs for 2.13.7...

**Review by joroKr21 — APPROVED** [review]
LGTM

**Comment by SethTisue** [comment]
closing without merging, since the purpose was just to gather feedback. the text will show up later this week at https://github.com/scala/scala/releases/tag/v2.13.8

**Pull request closed without merging**
