### PR TITLE
Make the release template into a GitHub issue template

### PR DESCRIPTION
**Pull request by dwijnand**
## Clicking "New issue" you get:

image

## Which leads to:

image

## Try it for yourself

* <https://github.com/dwijnand/scala-dev/issues/new/choose>
* <https://github.com/dwijnand/scala-dev/issues/new?template=release.md&title=Release+2.y.z>

WDYT?

### CODE REVIEW

**Comment by dwijnand** [comment]
If this is of interest, ping me and we can re-open this proposal 😄

**Comment by SethTisue** [comment]
LGTM, there's no reason we shouldn't do this, right? @adriaanm?

**Comment by adriaanm** [comment]
Ah, cool!

**Review by adriaanm — APPROVED** [review]

**Comment by adriaanm** [comment]
Thanks, could you resolve the conflict and merge?

**Comment by dwijnand** [comment]
Done (the wrong way: straight pushed to here rather than my fork, whoops)

https://github.com/scala/scala-dev/commit/4a649cbf803f090736aa4582fee92b931c561f59

**Comment by dwijnand** [comment]
Btw, if you find it annoying that clicking "New issue" gives you a big button for releases and a tiny link for general issues we can add an empty template for general issues:

```markdown
---
name: General issue
about: An empty template for general issues
---

```

**Pull request closed without merging**
